[provider]
expression = 'render(settings.template, { icon: context.data.icon, percent: format_percent(context.data.percent), status: context.data.status })'

[[triggers.on_source]]
id = "sample"
source = "battery"
event = "sample"

[settings]
template = "#battery(@pill){ [  ][{icon} ](@green)[{percent}][  ] }"
interval = "30s"
