blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions / Community Ideas
    url: https://github.com/xavialyra/cellbar/discussions
    about: Please ask questions and discuss new ideas or configurations here!
